# Generated by Django 2.1.4 on 2018-12-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
